package com.college.booking.enums;

public enum NotificationType {
    BOOKING_SUBMITTED,
    PROFESSOR_APPROVAL,
    ADMIN_APPROVAL,
    BOOKING_CONFIRMED,
    BOOKING_REJECTED,
    BOOKING_CANCELLED,
    UPCOMING_BOOKING,
    CHECKIN_REMINDER,
    WAITLIST_AVAILABLE,
    MAINTENANCE_NOTICE,
    ISSUE_UPDATE,
    SYSTEM
}
